country="US"
ctrl_interface=/var/run/wpa_supplicant_s1g
sae_pwe=0
max_peer_links=10
mesh_fwding=0
network={
    ssid="MESH"
    key_mgmt=SAE
    mode=5
    channel=12
    op_class=71
    country="US"
    s1g_prim_chwidth=1
    s1g_prim_1mhz_chan_index=0
    dtim_period=1
    mesh_rssi_threshold=-85
    dot11MeshHWMPRootMode=0
    dot11MeshGateAnnouncements=0
    mbca_config=1
    mbca_min_beacon_gap_ms=25
    mbca_tbtt_adj_interval_sec=60
    dot11MeshBeaconTimingReportInterval=10
    mbss_start_scan_duration_ms=2048
    mesh_beaconless_mode=0
    mesh_dynamic_peering=1
    sae_password="12345678"
    pairwise=CCMP
    ieee80211w=2
    beacon_int=1000
    group_rekey=0
}
