options morse enable_ps=0 enable_dynamic_ps_offload=N enable_auto_duty_cycle=N enable_twt=N
options morse enable_mcast_whitelist=0 enable_mcast_rate_control=1
options morse country=US
options morse bcf=bcf_fgh100mhaamd.bin
options morse spi_clock_speed=1500000
